// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// Docs site config (ROADMAP.md Phase 10 — migrated from MkDocs Material to
// Starlight). Content under src/content/docs/ (besides index.mdx) is
// generated by ../../scripts/docs_prepare.py from this repo's existing
// markdown — see that script's docstring and .gitignore.
export default defineConfig({
  site: "https://jazicorn.github.io",
  base: "/pokemon-trainer-platform-ai",
  integrations: [
    starlight({
      title: "Pokemon Trainer Platform - AI",
      description:
        "Multi-agent Pokemon trade advisor — CLI, MCP server, and public HTTP API.",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/jazicorn/pokemon-trainer-platform-ai",
        },
      ],
      customCss: ["./src/styles/theme.css", "./src/styles/type-tokens.css"],
      components: {
        SiteTitle: "./src/components/SiteTitle.astro",
        PageTitle: "./src/components/PageTitle.astro",
      },
      sidebar: [
        { label: "Overview", link: "/overview/" },
        { label: "Getting Started", link: "/getting-started/" },
        { label: "Onboarding", items: [{ autogenerate: { directory: "onboarding" } }] },
        { label: "Architecture", link: "/architecture/" },
        { label: "Reference", items: [{ autogenerate: { directory: "reference" } }] },
        { label: "Troubleshooting", items: [{ autogenerate: { directory: "troubleshooting" } }] },
        {
          label: "CLI Build Walkthrough",
          items: [{ autogenerate: { directory: "walkthrough-cli" } }],
        },
        {
          label: "Roadmap",
          items: [
            { label: "Web API (Phases 1-16)", link: "/roadmap/web-api/" },
            { label: "Platform, Launch & Growth (Phases 17-29)", link: "/roadmap/platform/" },
          ],
        },
        { label: "History", link: "/history/" },
        { label: "Changelog", link: "/changelog/" },
      ],
    }),
  ],
});
